apiVersion: v1
kind: Service
metadata:
  name: mlops-api-sinerror-service
spec:
  selector:
    app: mlops-api-sinerror
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 6000 
  type: ClusterIP
